select * from funcionario;

SELECT CODIGOFUNCIONARIO, NOME
FROM FUNCIONARIO
WHERE SALARIO=
    (SELECT MAX(SALARIO)
    FROM FUNCIONARIO);

SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO
WHERE SALARIO >
    (SELECT AVG(SALARIO)
    FROM FUNCIONARIO);

SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO
WHERE SALARIO<
    (SELECT AVG(SALARIO)
    FROM FUNCIONARIO
    WHERE CODIGODEPARTAMENTO IN (SELECT CODIGODEPARTAMENTO
        FROM DEPARTAMENTO
        WHERE NOME='Tecnologia da Informação'));


SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO
WHERE SALARIO<
    (SELECT AVG(SALARIO)
    FROM FUNCIONARIO F JOIN DEPARTAMENTO D ON
        (F.CODIGODEPARTAMENTO=D.CODIGODEPARTAMENTO)
    WHERE D.NOME='Tecnologia da Informação');


SELECT COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
WHERE SALARIO <
    (SELECT MAX(SALARIO)
    FROM FUNCIONARIO
    WHERE SEXO='F');

SELECT COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
WHERE SALARIO in
    (SELECT SALARIO
    FROM FUNCIONARIO
    WHERE SEXO='F');

