CREATE TABLE NIVEL
(CODIGONIVEL INT PRIMARY KEY, DESCRICAO VARCHAR(90))

CREATE TABLE CURSO
(CODIGOCURSO INT PRIMARY KEY, NOME VARCHAR(90), DATACRIACAO DATE NULL)

ALTER TABLE CURSO 
ADD COLUMN CODIGONIVEL INT 
ADD CONSTRAINT CODIGONIVEL_FK 
FOREIGN KEY (CODIGONIVEL)
REFERENCES NIVEL (CODIGONIVEL)

INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (1,'Graduação');
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (2,'Especialização');
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (3,'Mestrado');
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (4,'Doutorado');

INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (1, 'Sistemas de Informação', '19/06/1999',1);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (2, 'Medicina', '10/05/1990',1);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (3, 'Nutrição', '19/02/2012',NULL);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (4, 'Pedagogia','19/06/1999',1);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (5, 'Saúde da Família','10/09/1999',3);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (6, 'Computacão Aplicada','10/09/1999', NULL);

SELECT * FROM NIVEL

SELECT * FROM CURSO

--PRODUTO CARTESIANO 2 FORMA

SELECT *
FROM CURSO, NIVEL

SELECT * 
FROM CURSO CROSS JOIN NIVEL

--JUNÇÃO INTERNA 2 FORMAS

SELECT *
FROM CURSO, NIVEL
WHERE NIVEL.CODIGONIVEL=CURSO.CODIGONIVEL

SELECT *
FROM CURSO 
	 INNER JOIN NIVEL ON (NIVEL.CODIGONIVEL=CURSO.CODIGONIVEL)

SELECT * 
FROM CURSO INNER JOIN NIVEL USING (CODIGONIVEL) -- NOME IGUAIS DAS CHAVES

SELECT *
FROM CURSO
	 NATURAL JOIN NIVEL -- NOME IGUAIS


SELECT CURSO.CODIGOCURSO, CURSO.NOME, NIVEL.CODIGONIVEL, NIVEL.DESCRICAO
FROM CURSO INNER JOIN NIVEL ON (NIVEL.CODIGONIVEL = CURSO.CODIGONIVEL)

--ALIAS DE TABELA

SELECT C.CODIGOCURSO, C.NOME, N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C
		INNER JOIN NIVEL N ON N.CODIGONIVEL=C.CODIGONIVEL


SELECT C.CODIGOCURSO, C.NOME, N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C 
	FULL JOIN NIVEL N ON (N.CODIGONIVEL=C.CODIGONIVEL) ;

SELECT *
FROM CURSO C 
	RIGHT JOIN NIVEL N ON (N.CODIGONIVEL=C.CODIGONIVEL) ;





