SELECT * FROM FUNCIONARIO

SELECT SEXO
FROM FUNCIONARIO
GROUP BY SEXO;

SELECT SEXO, COUNT(*) AS QUANTIDADE , NOME
FROM FUNCIONARIO
GROUP BY SEXO, NOME

INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (6, 'ROBERTA SILVA BRASIL', '82998', 'F', '20/02/1980',7000);