SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO F
WHERE SALARIO >
    (SELECT AVG(SALARIO)
    FROM FUNCIONARIO
    WHERE CODIGODEPARTAMENTO=F.CODIGODEPARTAMENTO);


	
SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO F
    JOIN
        (SELECT CODIGODEPARTAMENTO,AVG(SALARIO) AS MEDIA
        FROM FUNCIONARIO
        GROUP BY CODIGODEPARTAMENTO) TESTE
    ON F.CODIGODEPARTAMENTO=TESTE.CODIGODEPARTAMENTO
WHERE SALARIO>MEDIA;

UPDATE FUNCIONARIO F
SET SALARIO=
    (SELECT MAX(SALARIO)
    FROM FUNCIONARIO
    WHERE CODIGODEPARTAMENTO=F.CODIGODEPARTAMENTO)
WHERE F.CODIGODEPARTAMENTO IS NOT NULL;
commit;
select * from funcionario