--â€¢LISTAR TODOS OS DADOS DOS DEPARTAMENTOS DE DA REGIÃƒO EM QUE ESTÃƒO LOCALIZADOS
SELECT *
FROM DEPARTAMENTO D 
     INNER JOIN   REGIAO R  ON D.ID_REGIAO = R.ID_REGIAO


--â€¢LISTAR TODOS OS DADOS DOS DEPARTAMENTOS DE DA REGIÃƒO EM QUE ESTÃƒO NA SINTAXE TRADICIONAL
SELECT *
FROM DEPARTAMENTO D,  REGIAO R  
WHERE D.ID_REGIAO = R.ID_REGIAO


--LISTAR O ID DO ENPREGADO, O SOBRENOME DO EMPREGADO, O ID DO DEPARTAMENTO, O NOME DO DEPARTAMENTO E O NOME DA REGIAO ONDE ESTÃ LOCALIZADO O DEPARTAMENTO
SELECT E.ID, E.ULT_NOME,D.ID, D.NOME, R.NOME
FROM EMPREGADO E
     INNER JOIN DEPARTAMENTO D ON E.ID_DEPTO = D.ID
     INNER JOIN REGIAO R ON D.ID_REGIAO = R.ID_REGIAO


--LISTAR TODOS OS DADOS DOS DEPARTAMENTOS DE DA REGIÃƒO UTILIZANDO USING
SELECT *
FROM DEPARTAMENTO 
     INNER JOIN REGIAO R  USING (ID_REGIAO)