
--LISTAR TODOS OS DADOS DOS SALÃ•ES CUJO ÃREA SEJA MAIOR QUE A ÃREA MÃ‰DIA DOS SALÃ•ES DO MESMO ANDAR
SELECT *
FROM SALOES E
WHERE AREA > (SELECT AVG(AREA) FROM SALOES I
              WHERE I.ANDAR = E.ANDAR)



--LISTAR TODOS OS DADOS DO AUTORES QUE POSSUEM OBRAS UTILIZANDO TESTE DE EXISTÃŠNCIA
SELECT *
FROM AUTORES E
WHERE EXISTS ( SELECT CODIGO FROM OBRAS I 
               WHERE I.AUTOR = E.CODIGO)

--LISTAR TODOS OS DADOS DO AUTORES QUE NÃƒO POSSUEM OBRAS UTILIZANDO TESTE DE EXISTÃŠNCIA
SELECT *
FROM AUTORES E
WHERE NOT EXISTS ( SELECT CODIGO FROM OBRAS I 
               WHERE I.AUTOR = E.CODIGO)


--LISTAR TODOS OS DADOS OS AUTORES QUE POSSUEM MAIS PINTURAS QUE ESCULTURAS
SELECT * FROM AUTORES A
WHERE  (SELECT COUNT(*) FROM OBRAS O INNER JOIN PINTURAS USING(CODIGO)
	   WHERE O.AUTOR = A.CODIGO ) >
	   (SELECT COUNT(*) FROM OBRAS O INNER JOIN ESCULTURAS USING(CODIGO)
	   WHERE O.AUTOR = A.CODIGO )
