/*OPERADORES DE CONJUNTO - UNION, INTERSECT e EXCEPT - 
TABELAS TEM QUE SER COMPATIVEIS - MESMA COLUNAS NAS MESMA ORDEM 
*/
SELECT * FROM CLIENTE

--CONSULTA UNION
-- RETORNAR O NOME E O CPF DE TODOS OS FUNCIONARIOS E CLIENTES
SELECT NOME, CPF
FROM FUNCIONARIO
UNION
SELECT NOME, CPF
FROM CLIENTE;


--UNION ALL NAO ELIMINA OS DUBLICADOS
SELECT NOME, CPF
FROM FUNCIONARIO
UNION ALL
SELECT NOME, CPF
FROM CLIENTE;


SELECT NOME, CPF, 'Dados da tabela FUNCIONARIO' AS ORIGEM
FROM FUNCIONARIO
UNION ALL
SELECT NOME, CPF, 'Dados da tabela CLIENTE' AS ORIGEM
FROM CLIENTE;

--LISTAR O NUMERO DOS SALOES QUE POSSUEM OBRAS OU QUE POSSUEM FUNCIONARIOS ALOCADOS
SELECT SALAO FROM OBRAS
UNION
SELECT NUMERO FROM ALOCACOES

---LISTAR O NUMERO DOS SALOES QUE POSSUEM OBRAS OU QUE POSSUEM FUNCIONARIOS ALOCADOS LISTANDO OS DUPLICADOS
SELECT SALAO FROM OBRAS
UNION ALL
SELECT NUMERO FROM ALOCACOES


---LISTAR O CODIGO DAS OBRAS DO ESTILO IMPRESSIONISTA OU FEITAS DE ARGILA 
SELECT CODIGO FROM PINTURAS WHERE UPPER(ESTILO) = 'IMPRESSIONISTA'
UNION
SELECT CODIGO FROM ESCULTURAS WHERE UPPER(MATERIAL) = 'ARGILA'


--LISTAR O CODIGO DAS OBRAS DO ESTILO IMPRESSIONISTA OU FEITAS DE ARGILA REPETINDO OS DUPLICADOS
SELECT CODIGO FROM PINTURAS WHERE UPPER(ESTILO) = 'IMPRESSIONISTA'
UNION
SELECT CODIGO FROM ESCULTURAS WHERE UPPER(MATERIAL) = 'ARGILA'


---LISTAR O TITULO E O NOME DO AUTOR CUJAS OBRAS SÃƒO DO ESTILO IMPRESSIONISTA OU FEITAS DE ARGILA
SELECT A.NOME, O.TITULO
FROM AUTORES A 
     INNER JOIN OBRAS O ON A.CODIGO = O.AUTOR
WHERE O.CODIGO IN 
(SELECT CODIGO FROM PINTURAS WHERE UPPER(ESTILO) = 'IMPRESSIONISTA'
UNION
SELECT CODIGO FROM ESCULTURAS WHERE UPPER(MATERIAL) = 'ARGILA')

