CREATE TABLE EMPREGADO 
(ID NUMERIC(7) NOT NULL PRIMARY KEY,
ULT_NOME VARCHAR(20) NOT NULL,
PRIM_NOME VARCHAR(20) NOT NULL,
CARGO VARCHAR(30), 
DT_ADMISSAO DATE,
CPF CHAR(11) UNIQUE,
ID_DEPARTAMENTO NUMERIC(7) REFERENCES DEPARTAMENTO(ID),
ID_GERENTE NUMERIC(7) REFERENCES EMPREGADO(ID)
);

CREATE TABLE DEPARTAMENTO 
(ID NUMERIC(7) PRIMARY KEY,
NOME VARCHAR(20) NOT NULL
);

SELECT * FROM DEPARTAMENTO