--Retornando empregado com ID > 3

SELECT * FROM EMPREGADO WHERE ID > 3;

--Retornando ID do cliente Ponto Quente

SELECT ID FROM CLIENTE  WHERE NOME = 'PONTO QUENTE'

SELECT ID FROM CLIENTE WHERE NOME = 'Ponto Quente'

SELECT ID FROM CLIENTE WHERE UPPER(NOME) = 'PONTO QUENTE'

--Filtrando por data

SELECT ULT_NOME, DT_ADMISSAO FROM EMPREGADO WHERE DT_ADMISSAO = '3/3/2009';

--Filtrando com vÃ¡rias condiÃ§Ãµes

SELECT ID, PRIM_NOME, DT_ADMISSAO, SALARIO
FROM EMPREGADO 
WHERE DT_ADMISSAO > '1/1/2010' AND SALARIO > 1000;

SELECT ID, PRIM_NOME, DT_ADMISSAO, SALARIO
FROM EMPREGADO 
WHERE DT_ADMISSAO > '1/1/2010' OR SALARIO > 1000;


--Uso do IN

SELECT ID, ULT_NOME, ID_DEPTO 
FROM EMPREGADO 
WHERE ID_DEPTO IN (10,30)

SELECT ID, ULT_NOME, ID_DEPTO 
FROM EMPREGADO 
WHERE ID_DEPTO NOT IN (10,30)

--Uso do BETWEEN

SELECT  ID, ULT_NOME, SALARIO 
FROM EMPREGADO
WHERE SALARIO BETWEEN 8000 AND 19500

SELECT  ID, ULT_NOME, SALARIO 
FROM EMPREGADO
WHERE SALARIO NOT BETWEEN 8000 AND 19500

--Uso de LIKE
SELECT ID, ULT_NOME
FROM EMPREGADO 
WHERE UPPER(ULT_NOME) LIKE '_E%'

SELECT ID, ULT_NOME
FROM EMPREGADO 
WHERE UPPER(ULT_NOME) NOT LIKE '_E%'

--Uso de IS NULL

SELECT * 
FROM CLIENTE
WHERE VENDEDOR  IS NULL

SELECT * 
FROM CLIENTE
WHERE VENDEDOR  IS NOT NULL


--Ordenando a consulta

SELECT ID, ULT_NOME, ID_DEPTO, SALARIO
FROM EMPREGADO
ORDER BY ID_DEPTO DESC, SALARIO 


SELECT ID, ULT_NOME, ID_DEPTO, SALARIO
FROM EMPREGADO




