-- INTERSECT É A AREA COMUM 

-- RETORNAR O NOME E O CPF DE TODOS OS CIDADAOS QUE SAO FUNCIONARIO E CLIENTES
SELECT NOME, CPF
FROM FUNCIONARIO
INTERSECT
SELECT NOME, CPF
FROM CLIENTE;

SELECT NOME, CPF
FROM FUNCIONARIO
INTERSECT
SELECT NOME, CPF
FROM CLIENTE
INTERSECT
SELECT NOME, CPF
FROM ALUNO;


SELECT NOME, CPF
FROM ALUNO
INTERSECT
SELECT NOME, CPF
FROM CLIENTE

