--LISTAR TODOS OS DADOS DOS AUTORES E DE SUAS OBRAS 
SELECT *
FROM AUTORES A 
     INNER JOIN OBRAS O
     ON A.CODIGO = O.AUTOR

--LISTAR O CÃ“DIGO O TÃTULO E O NOME DO AUTOR DAS OBRAS DE 1965 A 1975 QUE ESTÃƒO NO SALÃƒO 36
SELECT O.CODIGO, O.TITULO,A.NOME
FROM AUTORES A 
     INNER JOIN OBRAS O
     ON A.CODIGO = O.AUTOR
WHERE SALAO = 36 AND ANO BETWEEN 1965 AND 1975

--LISTAR O NOME E A NACIONALIDADE DOS AUTORES QUE POSSUEM OBRAS EXPOSTAS, RESOLVER POR JUNÃ‡ÃƒO
SELECT DISTINCT A.NOME, A.NACIONALIDADE
FROM AUTORES A
     INNER JOIN OBRAS O ON A.CODIGO = O.AUTOR

--LISTAR O CÃ“DIGO E O TÃTULO DAS OBRAS DO AUTOR PABLO PICASSO QUE SE ENCONTRAM NO TERCEIRO ANDAR DO MUSEU
SELECT O.CODIGO, O.TITULO
FROM AUTORES A
     INNER JOIN OBRAS O ON A.CODIGO = O.AUTOR
     INNER JOIN SALOES S ON S.NUMERO = O.SALAO
WHERE UPPER(A.NOME) = 'PABLO PICASSO' AND S.ANDAR = 3

--LISTAR O NOME E A NACIONALIDADE DOS AUTORES, O TÃTULO DA OBRA E O ESTILO DA PINTURA
SELECT A.NOME, A.NACIONALIDADE, O.TITULO, P.ESTILO
FROM AUTORES A
     INNER JOIN OBRAS O ON A.CODIGO = O.AUTOR
     INNER JOIN PINTURAS P ON P.CODIGO = O.CODIGO

--LISTAR O TÃTULO DA OBRA E O ESTILO DA PINTURA UTILIZANDO JUNÃ‡ÃƒO USING
SELECT  O.TITULO, P.ESTILO
FROM OBRAS O 
     INNER JOIN PINTURAS P USING(CODIGO)


--LISTAR O TÃTULO DA OBRA E O ESTILO DA PINTURA UTILIZANDO JUNÃ‡ÃƒO TRADICIONAL

SELECT  O.TITULO, P.ESTILO
FROM OBRAS O , PINTURAS P
WHERE P.CODIGO = O.CODIGO

--LISTAR O NOME E A NACIONALIDADE DOS AUTORES QUE NÃƒO POSSUEM OBRAS EXPOSTAS, RESOLVER POR JUNÃ‡ÃƒO
SELECT DISTINCT A.NOME, A.NACIONALIDADE
FROM AUTORES A
     LEFT JOIN OBRAS O ON A.CODIGO = O.AUTOR
WHERE O.CODIGO IS NULL

--LISTAR TODOS OS DADOS DOS SALÃ•ES QUE NÃƒO POSSUEM OBRAS EXPOSTAS
SELECT S.*
FROM SALOES S 
     LEFT JOIN OBRAS O ON S.NUMERO = O.SALAO
WHERE O.SALAO IS NULL

--LISTAR O CÃ“DIGO E O TÃTULO DAS OBRAS IMPRESSIONISTAS OU CUJO MATERIAL DE FABRICAÃ‡ÃƒO Ã‰ ARGILA, RESOLVA POR JUNÃ‡ÃƒO;
SELECT O.CODIGO, O.TITULO
FROM ESCULTURAS E
     RIGHT JOIN OBRAS O ON E.CODIGO = O.CODIGO
     LEFT JOIN PINTURAS P ON P.CODIGO = O.CODIGO
WHERE UPPER(E.MATERIAL) = 'ARGILA' OR UPPER (P.ESTILO) = 'IMPRESSIONISTA'

--LISTAR OS DADOS DOS FUNCIONARIOS QUE ESTÃƒO ALOCADOS COM OS DADOS DA ALOCAÃ‡ÃƒO E TAMBEM OS DADOS DOS NÃƒO ALOCADOS
SELECT * 
FROM FUNCIONARIOS F
     LEFT JOIN ALOCACOES A ON F.CPF = A.CPF


