--LISTAR O NUMERO DOS SALOES QUE POSSUEM OBRAS OU QUE POSSUEM FUNCIONARIOS ALOCADOS
SELECT SALAO FROM OBRAS -- SALAO QUE TEM OBRAS
UNION
SELECT NUMERO FROM ALOCACOES -- SALOES QUE TEM FUNCIONARIOS ALOCADOS

---LISTAR O NUMERO DOS SALOES QUE POSSUEM OBRAS OU QUE POSSUEM FUNCIONARIOS ALOCADOS LISTANDO OS DUPLICADOS
SELECT SALAO FROM OBRAS
UNION ALL
SELECT NUMERO FROM ALOCACOES
ORDER BY 1

---LISTAR O CODIGO DAS OBRAS DO ESTILO IMPRESSIONISTA OU FEITAS DE ARGILA 
SELECT CODIGO FROM PINTURAS WHERE UPPER(ESTILO) = 'IMPRESSIONISTA'
UNION
SELECT CODIGO FROM ESCULTURAS WHERE UPPER(MATERIAL) = 'ARGILA'


--LISTAR O CODIGO DAS OBRAS DO ESTILO IMPRESSIONISTA OU FEITAS DE ARGILA REPETINDO OS DUPLICADOS
SELECT CODIGO FROM PINTURAS WHERE UPPER(ESTILO) = 'IMPRESSIONISTA'
UNION
SELECT CODIGO FROM ESCULTURAS WHERE UPPER(MATERIAL) = 'ARGILA'


---LISTAR O TITULO E O NOME DO AUTOR CUJAS OBRAS SÃƒO DO ESTILO IMPRESSIONISTA OU FEITAS DE ARGILA
SELECT A.NOME, O.TITULO
FROM AUTORES A 
     INNER JOIN OBRAS O ON A.CODIGO = O.AUTOR
WHERE O.CODIGO IN 
(SELECT CODIGO FROM PINTURAS WHERE UPPER(ESTILO) = 'IMPRESSIONISTA'
UNION
SELECT CODIGO FROM ESCULTURAS WHERE UPPER(MATERIAL) = 'ARGILA')

