--LISTAR TODOS OS DADOS DE FUNCIONÃRIOS CUJO SALARIO SEJA MAIOR QUE O SALARIO MÃ‰DIO DE TODOS OS FUNCIONÃRIOS
SELECT * 
FROM FUNCIONARIOS
WHERE SALARIO > (SELECT AVG(SALARIO) FROM FUNCIONARIOS)

--LISTAR TODOS OS DADOS DOS SALÃ•ES QUE POSSUEM OBRAS EXPOSTAS.
SELECT *
FROM SALOES
WHERE NUMERO IN (SELECT SALAO FROM OBRAS)

--LISTAR TODOS OS DADOS DOS SALÃ•ES QUE NÃƒO POSSUEM OBRAS EXPOSTAS
SELECT *
FROM SALOES
WHERE NUMERO NOT IN (SELECT SALAO FROM OBRAS WHERE SALAO IS NOT NULL)

--LISTAR OS DADOS DOS AUTORES QUE NÃƒO POSSUEM OBRAS EXPOSTAS NO MUSEU
SELECT * 
FROM AUTORES
WHERE CODIGO NOT IN (SELECT AUTOR FROM OBRAS WHERE AUTOR IS NOT NULL)

--LISTAR TODOS OS DADOS DOS FUNCIONARIOS QUE POSSUEM ALGUM ALOCAÃ‡ÃƒO
SELECT * 
FROM FUNCIONARIOS 
WHERE CPF IN (SELECT CPF FROM ALOCACOES WHERE CPF IS NOT NULL)

--LISTAR TODOS OS DADOS DOS FUNCIONARIOS QUE NÃƒO POSSUEM ALGUM ALOCAÃ‡ÃƒO
SELECT * 
FROM FUNCIONARIOS 
WHERE CPF  NOT IN (SELECT CPF FROM ALOCACOES WHERE CPF IS NOT NULL)


