CREATE TABLE ALUNO --CRIANDO UM TABELA ALUNO
(CODIGOALUNO INT NOT NULL, 
NOME VARCHAR(90) NOT NULL, 
SEXO CHAR(1) NOT NULL, 
DTNASCIMENTO DATE NOT NULL, 
EMAIL VARCHAR(30) NULL,
CONSTRAINT ALUNO_PK PRIMARY KEY (CODIGOALUNO));-- CHAVE PRIMARIA

INSERT INTO ALUNO --INSERINDO CONTEUDO NAS LINHAS
(CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (1,'JOSÉ FRANCISCO TERRA','M','28/10/1989','JFT@GMAIL.COM');
INSERT INTO ALUNO 
(CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (2,'ANDREY COSTA FILHO','M','20/10/1999','ANDREYCF@HOTMAIL.COM');
INSERT INTO ALUNO 
(CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (3,'PATRÍCIA TORRES LOUREIRO','F','20/10/1980',
'PTORRES@GMAIL.COM');
INSERT INTO ALUNO 
(CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (4,'CARLA MARIA MACIEL','F','20/11/1996',NULL);
INSERT INTO ALUNO 
(CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (5,'LEILA SANTANA COSTA','F','20/11/2001',NULL);

SELECT * FROM ALUNO --SELECT BASICO O * RETORNA TODAS AS COLUNAS

SELECT CODIGOALUNO, NOME, DTNASCIMENTO
FROM ALUNO; 

SELECT CODIGOALUNO AS "Matrícula", -- renomea as colunas
NOME AS "Nome do discente",
DTNASCIMENTO AS "Data de nascimento"
FROM ALUNO

SELECT NOME ||' '|| EMAIL FROM ALUNO -- CONCATENAÇÃO DAS COLUNAS

SELECT 5 + 9, 'ALO MUNDO' --PARA MANDAR UMA MENSAGEM

--FUNÇOES DATA E HORA
SELECT CURRENT_DATE AS "Data Atual",
 CURRENT_TIME AS "Hora Atual",
 CURRENT_TIMESTAMP "Data e Hora atuais",
-- DOW 0 - domingo, 1 - segunda, ..., 6 - sábado
 EXTRACT( DOW FROM CURRENT_DATE) AS "Dia da semana",
 EXTRACT( DAY FROM CURRENT_DATE) AS "Dia Atual",
 EXTRACT( DOY FROM CURRENT_DATE) AS "Dia do ano",
 EXTRACT( MONTH FROM CURRENT_DATE) AS "Mês Atual",
 EXTRACT( YEAR FROM CURRENT_DATE) AS "Ano Atual",
 EXTRACT( CENTURY FROM CURRENT_DATE) AS "Século Atual";

 SELECT --ESTRUTURA DE CASE, SE FOR 0 RETORNE DOMINGO
 CASE 
 WHEN extract(dow from current_date) = 0 THEN 'domingo'
 WHEN extract(dow from current_date) = 1 THEN 'segunda-feira'
 WHEN extract(dow from current_date) = 2 THEN 'terça-feira'
 WHEN extract(dow from current_date) = 3 THEN 'quarta-feira'
 WHEN extract(dow from current_date) = 4 THEN 'quinta-feira'
 WHEN extract(dow from current_date) = 5 THEN 'sexta-feira'
 WHEN extract(dow from current_date)= 6 THEN 'sábado'
 END AS "Nome do dia da semana";


SELECT NOME,DTNASCIMENTO, --IDADE DOS ALUNOS EM ANO MES E DIAS
AGE(DTNASCIMENTO) AS "Idade [ano/mês/dia]",
EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "Idade do Aluno"
FROM ALUNO;

SELECT NOME, --FAIXA ETARIA DE CADA ALUNO
EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "Idade do Aluno",
CASE WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) <=20 THEN '1. até 20 anos'
 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 21 AND 30 THEN '2. 21 a 30 anos'
WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 31 AND 40 THEN '3. 31 a 40 anos'
WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 41 AND 50 THEN '4. 41 a 50 anos'
 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 51 AND 60 THEN '5. 51 a 60 anos'
 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) > 60 THEN '6. mais de 60 anos'
 END AS "Faixa Etária"
FROM ALUNO;

--FUNÇÃO DE RESUMO COUNT

SELECT
COUNT(*) AS "Número de alunos",
MIN(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Menor Idade",
AVG(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Idade Média",
MAX(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Maior Idade",
SUM(EXTRACT(YEAR FROM AGE(DTNASCIMENTO)))/COUNT(*) AS "Soma idade"
FROM ALUNO;

SELECT COUNT(*), COUNT(NOME), COUNT (EMAIL) FROM ALUNO --CONTA A QUANTIDADE DE LINHAS PREENCHIDAS 

SELECT MIN(NOME), MAX(NOME), 
MIN(DTNASCIMENTO), MAX(DTNASCIMENTO), 
MIN(CODIGOALUNO), MAX(CODIGOALUNO)
FROM ALUNO;


CREATE TABLE DISCIPLINA 
(COD INT PRIMARY KEY,
NOME VARCHAR(30))

INSERT INTO DISCIPLINA VALUES (1,'D1');
INSERT INTO DISCIPLINA VALUES (2,'D2');
INSERT INTO DISCIPLINA VALUES (3,'D3');
INSERT INTO DISCIPLINA VALUES (4,'D4');

SELECT * FROM DISCIPLINA

CREATE TABLE CURSO
(COD INT PRIMARY KEY,
NOME VARCHAR(30));

INSERT INTO CURSO VALUES (1,'C1');
INSERT INTO CURSO VALUES (2,'C2');

SELECT COUNT(*) NCURSOS FROM CURSO; -- COMANDO SEPARADOS PARA MOSTRAR A QUANT DE LINHAS
SELECT COUNT(*) NDISCIPINAS FROM DISCIPLINA; 
SELECT COUNT(*) NALUNOS FROM ALUNO;

SELECT -- COMANDO QUE EXECUTA TUDO 
 (SELECT COUNT(*) NCURSOS FROM CURSO), 
 (SELECT COUNT(*) NALUNOS FROM ALUNO), 
 (SELECT COUNT(*) NDISCIPINAS FROM DISCIPLINA); 

CREATE TABLE TTESTE AS --CRIAR UMA TABELA APARTI DE UMA CONSULTA 
SELECT  NOME, 
  EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "Idade do Aluno", 
  CASE WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) <=20  THEN '1. até 20 anos' 
              WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 21 AND 30  THEN '2. 21 a 30 anos' 
       WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 31 AND 40  THEN '3. 31 a 40 anos' 
       WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 41 AND 50  THEN '4. 41 a 50 anos' 
             WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 51 AND 60  THEN '5. 51 a 60 anos' 
             WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) > 60  THEN '6. mais de 60 anos'     
    END AS "Faixa Etária" 
FROM ALUNO; 

SELECT * FROM TTESTE


CREATE VIEW VTESTE AS --VISAO DINAMICA SAO GERADOS NA HORA
SELECT  NOME, 
  EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "Idade do Aluno", 
  CASE WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) <=20  THEN '1. até 20 anos' 
             WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 21 AND 30  THEN '2. 21 a 30 anos' 
    WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 31 AND 40  THEN '3. 31 a 40 anos' 
    WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 41 AND 50  THEN '4. 41 a 50 anos' 
             WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 51 AND 60  THEN '5. 51 a 60 anos' 
          WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) > 60  THEN '6. mais de 60 anos'     
    END AS "Faixa Etária" 
FROM ALUNO;

SELECT * FROM VTESTE

SELECT * FROM ALUNO

DELETE FROM VTESTE

--USO DO WHERE

SELECT NOME, DTNASCIMENTO FROM ALUNO
WHERE SEXO ='F' --CONDIÇÃO

--MOSTRA O NOME E DATA DE NASCIMENTO DAS ALUNAS ANIVESARIO EM NOVEMBRO
SELECT NOME, DTNASCIMENTO FROM ALUNO
WHERE SEXO ='F' AND EXTRACT(MONTH FROM DTNASCIMENTO) = 11


-- USO DO IN E BETWEEN

SELECT NOME, DTNASCIMENTO --ALUNOS QUE NASCERAM NO SEGUNDO SEMESTRE
FROM ALUNO
WHERE EXTRACT (MONTH FROM DTNASCIMENTO) IN (7,8,9,10); -- RETORNA UM DOS VALORES QUE ESTAO DENTRO

SELECT NOME, DTNASCIMENTO --NOME DO ALUNO CUJO O ANO DE NASCIMENTO ESTA ENTRE 1985 E 2005
FROM ALUNO
WHERE EXTRACT (YEAR FROM DTNASCIMENTO) BETWEEN 1985 AND 2005;

SELECT NOME
FROM ALUNO
WHERE EXTRACT (YEAR FROM DTNASCIMENTO) >= 1985 AND EXTRACT (YEAR FROM DTNASCIMENTO) <= 2005;

--OPERADOR LIKE

SELECT * FROM ALUNO

SELECT NOME -- NOME DO ALUNO QUE CONTENHA COSTA
FROM ALUNO
WHERE NOME LIKE '%COSTA%';

SELECT NOME -- TODOS OS ALUNOS QUE A SEGUNDA LETRA É 'A'
FROM ALUNO
WHERE NOME LIKE '_A%';

SELECT NOME, DTNASCIMENTO -- LISTA OS NOME QUE NAO TEM MARIA
FROM ALUNO
WHERE NOME NOT LIKE '%MARIA%';

SELECT COUNT(*) AS QUANTIDADE --QUANTIDADE DE ALUNOS QUE TEM O GMAIL
FROM ALUNO
WHERE EMAIL  LIKE '%@GMAIL.%';


















