--LISTAR CÃ“DIGO DOS AUTORES QUE NÃƒO POSSUEM OBRAS EXPOSTAS NO MUSEU UTILIZANDO OPERADORES DE CONJUNTO
SELECT CODIGO FROM AUTORES
EXCEPT
SELECT AUTOR FROM OBRAS

--LISTAR CÃ“DIGO DOS AUTORES QUE  POSSUEM OBRAS EXPOSTAS NO MUSEU UTILIZANDO OPERADORES DE CONJUNTO
SELECT CODIGO FROM AUTORES
INTERSECT
SELECT AUTOR FROM OBRAS

--LISTAR O CÃ“DIGO DOS AUTORES QUE POSSUEM APENAS PINTURAS NO MUSEU UTILIZANDO OPERADORES DE CONJUNTO
SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM PINTURAS)
EXCEPT 
SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM ESCULTURAS)


--LISTAR O CÃ“DIGO DOS AUTORES QUE POSSUEM APENAS ESCULTURAS NO MUSEU UTILIZANDO OPERADORES DE CONJUNTO
SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM ESCULTURAS)
EXCEPT
SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM PINTURAS)

--LISTAR O CÃ“DIGO DOS ARTISTAS QUE POSSUEM OU APENAS ESCULTURAS OU APENAS PINTURAS UTILIZANDO OPERADORES DE CONJUNTO 
(SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM PINTURAS)
EXCEPT 
SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM ESCULTURAS))
UNION
(SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM ESCULTURAS)
EXCEPT
SELECT AUTOR FROM OBRAS WHERE CODIGO IN (SELECT CODIGO FROM PINTURAS))