n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Tem só espaço', n.isspace())
print('É um numero? ',n.isnumeric())
print('É alfanumérico? ',n.isalnum())
print('É alfabético? ',n.isalpha())
print ('Esta em maiusculas? ',n.isupper())
print('esta em minusculas? ',n.islower())
print('esta capitalizada? ',n.istitle())